# Generated by Django 2.0.1 on 2018-02-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drugbank_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('indication', models.CharField(max_length=1000)),
                ('moa', models.CharField(max_length=1000)),
                ('chembl_ID', models.CharField(max_length=20)),
                ('approval', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('uniprot_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('protein_name', models.CharField(max_length=100)),
                ('PDB_ID', models.CharField(max_length=5)),
                ('gene_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='targets',
            field=models.ManyToManyField(to='repos.Target'),
        ),
    ]
