# Generated by Django 2.0.1 on 2018-02-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbank_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_ID', models.CharField(max_length=200)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Drug')),
            ],
        ),
    ]
