# Generated by Django 2.0.1 on 2018-02-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drugbank_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('uniprot_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('protein_name', models.CharField(max_length=200)),
                ('PDB_ID', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Target'),
        ),
    ]
