# Generated by Django 2.0.1 on 2018-02-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='drug',
        ),
        migrations.AddField(
            model_name='drug',
            name='brand_name',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='PDB_ID',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='protein_name',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugbank_ID',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='target',
            name='uniprot_ID',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='interaction',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Drug'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Target'),
        ),
    ]
