# Generated by Django 2.0.1 on 2018-03-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='target_pair',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
    ]
